version: '3.2'

services:
  client-name:
    env_file: .env
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      # [CHANGE]: based on project port conflict
      - '4000:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true
